language: node_js

node_js:
 - "stable"

cache:
  directories:
    - "node_modules"

install:
  - yarn install
  - yarn install netlify-cli

jobs:
  include:
    - stage: "staging"
      if: type = "push"
      script:
        - npm run lint:start
        - npm run jest:start
    - stage: "production"
      if: type = pull_request
      script:
        - npm run lint:start
        - npm run jest:coverage
