# Production context: all deploys from the `master` branch set in your site's
# will inherit these settings.
[context.production.environment]
    ACCESS_TOKEN = "super secret",
    NODE_VERSION = "8.0.1"
